languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
baseUrl = "http://localhost"
theme = "anubis"
paginate = 10
disqusShortname = ""
googleAnalytics = ""
enableRobotsTXT = true
# enableInlineShortcodes = true
# pygmentsCodeFences = true
# pygmentsUseClasses = true
enableEmoji = true

[params]
  author = "Noam Kestin"
  email = "info@nokx.ch"
  avatar = "/images/avatar.png"
  description = "nokx website"
  # images = [ "images/og-featured.png" ]
  # customCSS = [ "css/my.css" ]
  # customJS = [ "js/main.js" ]
  dateFormat = "2006-01-02"
  paginationSinglePost = true
  style = "dark-without-switcher"
  readMore = false
  disableSummary = false
  utterancesRepo = ""
  utterancesTheme = ""
  utterancesIssue = ""
  utterancesLabel = ""
    [params.webmentions]
      # url = "https://nokx.ch"
      login = "hugo-theme-anubis"
      pingback = false

  [[params.social]]
    id = "email"
    name = "info@nokx.ch"
  [[params.social]]
    id = "linkedin"
    name = "noam-kestin-05nk"
  [[params.social]]
    id = "github"
    name = "nokx5"
  # [[params.social]]
  #   id = "telegram"
  #   name = "NonoKoukouk"

  [params.navigation]
    help = "Help"
    

[markup.goldmark.renderer]
  unsafe = true # enable raw HTML in Markdown

[markup.tableOfContents]
  ordered = false

[minify] # white space issue
  disableHTML = true



[languages.en]
  languageName = "English"
  title = "Home"
  weight = 1
  [[menu.main]]
    name = "blog"
    title = "blog"
    url = "/blog/"
    weight = 10
  
  [[menu.main]]
    name = "software"
    title = "software"
    url = "/software/"
    weight = 11
  
  [[menu.main]]
    name = "music"
    title = "music"
    # url = "/music/"
    weight = 12
  
  [[menu.main]]
    name = "contact"
    title = "contact"
    # url = "/contact/"
    weight = 13


[languages.fr]
  languageName = "Français"
  title = "Chez Nokx"
  weight = 2
  # [languages.fr.params]
  #   linkedin = "https://linkedin.com/fr/whoever"
  #   [languages.fr.params.navigation]
  #     help = "Aide"
  [[languages.fr.menu.main]]
    name = "journal de bord"
    title = "journal de bord"
    url = "/blog/"
    weight = 10
  
  [[languages.fr.menu.main]]
    name = "logiciel"
    title = "logiciel"
    url = "/software/"
    weight = 11
  
  [[languages.fr.menu.main]]
    name = "musique"
    title = "musique"
    url = "/music/"
    weight = 12
  
  [[languages.fr.menu.main]]
    name = "contact"
    title = "contact"
    url = "/contact/"
    weight = 13


[languages.he]
  languagedirection = "rtl"
  languageName = "עברית"
  title = "nokx ברוכים הבאים ל"
  author = "נועם קסטין"
  weight = 3
  # [languages.fr.params]
  #   linkedin = "https://linkedin.com/fr/whoever"
  #   [languages.fr.params.navigation]
  #     help = "Aide"
  [[languages.he.menu.main]]
    name = "בלוג"
    title = "בלוג"
    url = "/blog/"
    weight = 20
  
  [[languages.he.menu.main]]
    name = "תוכנות"
    title = "תוכנות"
    url = "/software/"
    weight = 19
  
  [[languages.he.menu.main]]
    name = "ג'ז"
    title = "ג'ז"
    url = "/music/"
    weight = 18
  
  [[languages.he.menu.main]]
    name = "קשר"
    title = "קשר"
    url = "/contact/"
    weight = 17


[languages.de]
  languageName = "Deutsch"
  title = "Willkommen !"
  weight = 4

  [[languages.de.menu.main]]
    name = "Blog"
    title = "Blog"
    # url = "/blog/"
    weight = 10
  
  [[languages.de.menu.main]]
    name = "Software"
    title = "Software"
    # url = "/software/"
    weight = 11
  
  [[languages.de.menu.main]]
    name = "Musik"
    title = "Musik"
    # url = "/music/"
    weight = 12
  
  [[languages.de.menu.main]]
    name = "Kontakt"
    title = "Kontakt"
    # url = "/contact/"
    weight = 13

# disableLanguages = ["he", "de"]

[taxonomies]
category = "categories"
tag = "tags"